builds:
  - binary: gce-sleep
    goos:
      - darwin
      - linux
    goarch:
      - amd64

fpm:
  vendor: Dom Udall
  homepage: https://domudall.co.uk/
  maintainer: Dom Udall <me@domudall.co.uk>
  description: Tool for shutting down/starting up Google Cloud Engine instances based on tags for savings costs when not in use.
  license: MIT
  formats:
    - deb
  files:
    "deb/etc/gce-sleep.conf": "/etc/gce-sleep.conf"
