version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.8

    working_directory: /go/src/github.com/domudall/gce-sleep
    steps:
      - checkout

      - run: go get github.com/Masterminds/glide
      - run: go get github.com/golang/dep/cmd/dep
      - restore_cache:
          keys:
            - dep-cache-{{ .Branch }}-{{ checksum "Gopkg.lock" }}
            - dep-cache-{{ .Branch }}
            - dep-cache
      - run: dep ensure
      - save_cache:
          key: dep-cache-{{ .Branch }}-{{ checksum "Gopkg.lock" }}
          paths:
            - vendor
      - save_cache:
          key: dep-cache-{{ .Branch }}
          paths:
            - vendor
      - save_cache:
          key: dep-cache
          paths:
            - vendor

      - run: go test $(glide nv)

  deploy:
    docker:
      - image: circleci/golang:1.8

    working_directory: /go/src/github.com/domudall/gce-sleep
    steps:
      - checkout

      - run: go get github.com/golang/dep/cmd/dep
      - restore_cache:
          keys:
            - dep-cache-{{ .Branch }}-{{ checksum "Gopkg.lock" }}
            - dep-cache-{{ .Branch }}
            - dep-cache
      - run: dep ensure
      - save_cache:
          key: dep-cache-{{ .Branch }}-{{ checksum "Gopkg.lock" }}
          paths:
            - vendor
      - save_cache:
          key: dep-cache-{{ .Branch }}
          paths:
            - vendor
      - save_cache:
          key: dep-cache
          paths:
            - vendor

      - run: curl -sL https://git.io/goreleaser | bash

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /^v[0-9]+(\.[0-9]+)*(-.*)*/
            branches:
              ignore: /.*/
