defaults: &defaults
  working_directory: /go/src/github.com/domudall/gce-sleep
  docker:
    - image: circleci/golang:1.8

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout

      - run: go get github.com/Masterminds/glide
      - run: go get github.com/golang/dep/cmd/dep

      - restore_cache:
          keys:
            - dep-cache-{{ .Branch }}-{{ checksum "Gopkg.lock" }}
            - dep-cache-{{ .Branch }}
            - dep-cache
      - run: dep ensure
      - save_cache:
          key: dep-cache-{{ .Branch }}-{{ checksum "Gopkg.lock" }}
          paths:
            - vendor
      - save_cache:
          key: dep-cache-{{ .Branch }}
          paths:
            - vendor
      - save_cache:
          key: dep-cache
          paths:
            - vendor

      - run: go test $(glide nv)

      - persist_to_workspace:
          root: /go/src/github.com/domudall
          paths:
            - gce-sleep

  deploy:
    <<: *defaults
    steps:
      - run: sudo apt-get install ruby ruby-dev rubygems build-essential
      - run: sudo gem install --no-ri --no-rdoc fpm

      - attach_workspace:
          at: /go/src/github.com/domudall/

      - run: curl -sL https://git.io/goreleaser | bash

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /^v[0-9]+(\.[0-9]+)*(-.*)*/
            branches:
              ignore: /.*/
