version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.8

    working_directory: /go/src/github.com/domudall/gce-sleep
    steps:
      - checkout

      - run: go get github.com/Masterminds/glide
      - run: go get github.com/golang/dep/cmd/dep
      - run: dep ensure
      - run: go test $(glide nv)

  deploy:
    docker:
      - image: circleci/golang:1.8

    working_directory: /go/src/github.com/domudall/gce-sleep
    steps:
      - run: curl -sL https://git.io/goreleaser | bash

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          # filters:
          #   tags: /v[0-9]+(\.[0-9]+)*(-.*)*/
